# Generated by Django 5.0 on 2023-12-20 20:20

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('base', models.FloatField()),
                ('height', models.FloatField()),
                ('area', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('base'), '*', models.F('height')), output_field=models.FloatField())),
            ],
        ),
    ]
