# Generated by Django 5.0 on 2023-12-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='sample',
        #     name='base',
        #     field=models.FloatField(default=1.0),
        #     preserve_default=False,
        # ),
    ]
