# Generated by Django 5.0 on 2023-12-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_rectangle_delete_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='rectangle',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
