# Generated by Django 5.0 on 2023-12-20 20:37

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_rectangle_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='rectangle',
            name='meat_sum',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('meta__qty'), '+', models.F('meta__price')), output_field=models.FloatField()),
        ),
    ]
