# Generated by Django 5.0 on 2023-12-20 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_rectangle_meat_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rectangle',
            old_name='meat_sum',
            new_name='meta_sum',
        ),
    ]
