# Generated by Django 5.0 on 2023-12-20 23:47

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_rename_meat_sum_rectangle_meta_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rectangle',
            name='meta_sum',
        ),
    ]
