# Generated by Django 5.0 on 2023-12-20 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_alter_rectangle_meta_sum'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='rectangle',
        #     name='meta_sum',
        # ),
    ]
