# Generated by Django 5.0 on 2023-12-20 23:49

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_remove_rectangle_meta_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='rectangle',
            name='meta_sum',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('meta__qty'), '*', models.F('meta__price')), output_field=models.FloatField()),
        ),
    ]
